[build]
  command = "cd client && npm install && npm run build"
  publish = "client/.next"
  base = "client"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 