import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import CommonLayout from "@/components/common/layout";
import AuthProvider from "@/components/providers/AuthProvider";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "AI Sapre Parts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${oswald.variable} ${roboto.variable}`}>
      <head>
        <meta name="permissions-policy" content="geolocation=(self), payment=(self), camera=(), microphone=()" />
      </head>
      <body>
        {/* <AuthProvider> */}
          <CommonLayout>{children}</CommonLayout>
          <Toaster />
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
